# Generated by Django 4.2.1 on 2024-02-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('nickename', models.CharField(max_length=8)),
            ],
        ),
    ]
