# Generated by Django 4.2.1 on 2024-02-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_pong', '0002_alter_userpong_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpong',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
