version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8001:5002
    env_file:
      - ./.env.queue
    volumes:
      - .:/app
    depends_on:
      - db
  
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    env_file:
      - ./.env.queue
    depends_on:
      - db
  
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      - MYSQL_DATABASE=main
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3307:3306