# Generated by Django 5.0.1 on 2024-04-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_userinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, default='static/src/img/avatar_user_icon2.png', null=True, upload_to='static/images/%Y/%m/%d/'),
        ),
    ]
