# Generated by Django 5.0.1 on 2024-05-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_userinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, default='static/images/astronaut3.jpeg', null=True, upload_to='static/images/%Y/%m/%d/'),
        ),
    ]
