# Generated by Django 5.0.1 on 2024-06-26 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_userinfo_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['-scores']},
        ),
    ]
