# Generated by Django 5.0.1 on 2024-06-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_userinfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, default='/media/avatars/default_avatar.jpeg', null=True, upload_to='media/avatars/'),
        ),
    ]
