# Generated by Django 5.0.1 on 2024-06-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_userinfo_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.CharField(blank=True, default='/media/avatars/default_avatar.jpeg', max_length=255),
        ),
    ]
