# Generated by Django 5.0.1 on 2024-06-27 03:35
from django.db import migrations, models
import uuid


users = [
    {
        "pk": 1,
        "fields": {
            "id_msc": uuid.UUID("38b8cb4d-34d8-4530-80f3-b4f10cf87b51"),
            "full_name": "Shelson",
            "nickname": "shelson",
            "scores": 48,
            "winnings": 16,
            "losses": 20,
            "position": 0,
            "status": False,
            "playing": False,
            "photo": "/media/avatars/shelson.jpeg",
        },
    },
    {
        "pk": 2,
        "fields": {
            "id_msc": uuid.UUID("9a72c344-62c3-49c3-9bca-188f6f7b3cbe"),
            "full_name": "Sheela",
            "nickname": "sheela",
            "scores": 64,
            "winnings": 22,
            "losses": 15,
            "position": 0,
            "status": False,
            "playing": False,
            "photo": "/media/avatars/sheela.png",
        },
    },
    {
        "pk": 3,
        "fields": {
            "id_msc": uuid.UUID("9c001ba9-14d5-45ff-a4a4-4f43234dcdd7"),
            "full_name": "Eliaris Raíra De Godoy Alvares",
            "nickname": "eliaris",
            "scores": 55,
            "winnings": 19,
            "losses": 19,
            "position": 0,
            "status": False,
            "playing": False,
            "photo": "/media/avatars/elraira-.jpeg",
        },
    },
    {
        "pk": 4,
        "fields": {
            "id_msc": uuid.UUID("355aaf65-0300-47b6-8748-c8d0c1aed702"),
            "full_name": "Bruno Bonaldi Ramos Silva",
            "nickname": "brunobonaldi",
            "scores": 50,
            "winnings": 17,
            "losses": 24,
            "position": 0,
            "status": False,
            "playing": False,
            "photo": "/media/avatars/brunobonaldi.jpeg",
        },
    },
    {
        "pk": 5,
        "fields": {
            "id_msc": uuid.UUID("e054f322-7733-48be-b1b1-7a66357efecd"),
            "full_name": "Humberto Arndt",
            "nickname": "humberto",
            "scores": 57,
            "winnings": 20,
            "losses": 16,
            "position": 0,
            "status": False,
            "playing": False,
            "photo": "/media/avatars/humberto.jpeg",
        },
    },
]


def forwards(apps, schema_editor):
    UserInfoModel: models.Model = apps.get_model("dashboard", "UserInfo")

    user_instances = [UserInfoModel(**user_data["fields"]) for user_data in users]
    UserInfoModel.objects.bulk_create(user_instances)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_alter_userinfo_photo"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
