# Generated by Django 5.0.1 on 2024-03-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_user_password"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="signinupoauth42dto",
            options={},
        ),
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(max_length=100),
        ),
    ]
