version: '3.7'

services:
  frontend:
    build: ./app_frontend
    container_name: frontend
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - ./app_frontend:/code
    ports:
      - "3000:3000"
    env_file:
      - .env.web

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: '1234'
    ports:
      - "5432:5432"

 
volumes:
  postgres_data:
