version: '3.7'

services:
  frontend:
    build: ./app_frontend
    container_name: frontend
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - ./app_frontend:/code
    ports:
      - "3000:3000"
    env_file:
      - .env.web
    depends_on:
      - user_management_api

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: '1234'
    ports:
      - "5432:5432"

  user_management_api:
    build: ./backend/services/user_management
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/services/user_management:/user_management
    ports:
      - "8000:8000"
    depends_on:
      - db
 
volumes:
  postgres_data:
