BBBB BBBB
BBBB BBBBBBBBBBBBBB

BB BBBB
  XXXX gettext(u'User Tournaments') XXXXX
BBBB
  XXXX gettext(u'Tournaments') XXXXX
BBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXX
    XXXXXXX
      XXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Date / Status') XXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Tournament Type') XXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Players') XXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Games') XXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Winner') XXXXX
        BB BBBB
           #

          XXXXXXXXX
           #

          XXXXXXXXX
        BBBBB
      XXXXX
    XXXXXXXX
    XXXXXXX
      BBB BBBBBBBBBB BB BBBBBBBBBBBBBBB
         #

          XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBB
              XXXXXXXXX
            BBBB
              XXXXXXXXX
            BBBBB
            XXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
            XXXX
              BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBB
                
              BBBB
                X
              BBBBB
            XXXXX
          XXXXX
         #

      BBBBBB
    XXXXXXXX
  XXXXXXXX
XXXXXX

BB BBBBBBBBBBBB
  
  
BBBBB
