version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: '1234'
    ports:
      - "5432:5432"

  user_management_api:
    build: ./services/user_management
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/user_management:/user_management
    ports:
      - "8000:8000"
    depends_on:
      - db
 
volumes:
  postgres_data:


