version: '3.8'

services:
  web:
    build: ./app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.web
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db

  auth-db:
    image: postgres
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_AUTH_DB}
    ports:
      - "5433:5432"

  auth-api:
    build: ./services/auth
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./services/auth:/code
    ports:
      - "8002:80"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_NAME=${POSTGRES_AUTH_DB}
      - POSTGRES_HOST=auth-db
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - auth-db

  user-management-api:
    container_name: user-management-api
    environment:
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - 8003:443

  game-api:
    container_name: game-api
    environment:
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - 8004:443
    
  user-stats-api:
    container_name: user-stats-api
    environment:
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - 8005:443

  gateway-api:
    container_name: gateway-api
    ports:
      - 8001:443
    environment:
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - auth-api 
      - user-management-api
      - game-api
      - user-stats-api

volumes:
  postgres_data:
  auth-db-data: