# Generated by Django 5.0.3 on 2024-05-02 00:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_datetime", models.DateTimeField(verbose_name="Game date")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Scheduled"),
                            (1, "Waiting players confirmation to beggin"),
                            (2, "Ongoing"),
                            (3, "Ended"),
                        ],
                        default=0,
                        verbose_name="Game status",
                    ),
                ),
                ("duration", models.DurationField(null=True)),
            ],
            options={
                "verbose_name_plural": "Games",
                "ordering": ["game_datetime"],
            },
        ),
        migrations.CreateModel(
            name="GameRules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("0", "Player winner points"),
                            ("1", "Game total points"),
                            ("2", "Game duration"),
                        ],
                        default="0",
                        max_length=1,
                        verbose_name="Game rule type",
                    ),
                ),
                (
                    "points_to_win",
                    models.PositiveSmallIntegerField(
                        blank=True, default=11, null=True, verbose_name="Points to win"
                    ),
                ),
                (
                    "game_total_points",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Game total points",
                    ),
                ),
                (
                    "max_duration",
                    models.DurationField(
                        blank=True,
                        default=datetime.timedelta(seconds=180),
                        null=True,
                        verbose_name="Game maximum duration",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Game Rules",
                "db_table": "core_game_rules",
            },
        ),
        migrations.AddConstraint(
            model_name="gamerules",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(("points_to_win__isnull", True), _negated=True),
                        models.Q(("game_total_points__isnull", True), _negated=True),
                        models.Q(("max_duration__isnull", True), _negated=True),
                        _connector="OR",
                    )
                ),
                name="all_rules_null",
                violation_error_message="At least one rule parameter must be setted",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="rules",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="core.gamerules",
                verbose_name="Game Rules",
            ),
        ),
    ]
