# Generated by Django 5.0.3 on 2024-04-10 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Date Due')),
                ('status', models.CharField(choices=[(0, 'Scheduled'), (1, 'Waiting players confirmation to beggin'), (2, 'On going'), (3, 'Ended')], default=0, max_length=1, verbose_name='Match status')),
                ('duration', models.DurationField()),
                ('score_a', models.PositiveSmallIntegerField(default=0, verbose_name='Player A Score')),
                ('score_b', models.PositiveSmallIntegerField(default=0, verbose_name='Player B Score')),
                ('player_reach_points', models.PositiveSmallIntegerField(default=11)),
                ('match_total_points', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('player_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchs_a', to='user.user', verbose_name='Player A')),
                ('player_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchs_b', to='user.user', verbose_name='Player B')),
            ],
            options={
                'verbose_name_plural': 'matchs',
            },
        ),
    ]
