# Generated by Django 5.0.3 on 2024-04-22 04:03

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    match = apps.get_model("core", "Match")
    match_rules = apps.get_model("core", "MatchRules")
    tournament = apps.get_model("core", "Tournament")

    mr = match_rules.objects.all().first()
    if mr:
        matchs = match.objects.all()
        for m in matchs:
            if not m.rules:
                m.rules = mr
                m.save()

        tournaments = tournament.objects.all()
        for t in tournaments:
            if not t.rules:
                t.rules = mr
                t.save()

def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_matchrules_challenge_elimination_leagueplayoff_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="match",
            name="rules",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="core.matchrules"
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="rules",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="tournament",
                to="core.matchrules",
            ),
        ),
    ]
