# Generated by Django 5.0.3 on 2024-04-22 20:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_match_rules_alter_tournament_rules'),
        ('user', '0002_rename_id_ref_user_id_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='rules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.matchrules', verbose_name='Match Rules'),
        ),
        migrations.AlterField(
            model_name='matchrules',
            name='match_total_points',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Match total points'),
        ),
        migrations.AlterField(
            model_name='matchrules',
            name='max_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=180), null=True, verbose_name='Match maximum duration'),
        ),
        migrations.AlterField(
            model_name='matchrules',
            name='player_reach_points',
            field=models.PositiveSmallIntegerField(blank=True, default=11, null=True, verbose_name='Points to win'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='matches',
            field=models.ManyToManyField(related_name='tournament', to='core.match', verbose_name='Matches'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(related_name='tournaments', to='user.user', verbose_name='Players'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rules',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='tournament', to='core.matchrules', verbose_name='Matches Rules'),
        ),
    ]
