# Generated by Django 5.0.3 on 2024-04-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_match_rules_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="matchrules",
            name="all_rules_null",
        ),
        migrations.RenameField(
            model_name="matchrules",
            old_name="player_reach_points",
            new_name="points_to_win",
        ),
        migrations.AddConstraint(
            model_name="matchrules",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(("points_to_win__isnull", True), _negated=True),
                        models.Q(("match_total_points__isnull", True), _negated=True),
                        models.Q(("max_duration__isnull", True), _negated=True),
                        _connector="OR",
                    )
                ),
                name="all_rules_null",
                violation_error_message="At least one rule parameter must be setted",
            ),
        ),
    ]
