# Generated by Django 5.0.3 on 2024-05-02 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_tournament_challenge_elimination_leagueplayoff_and_more"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="number_of_players",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterUniqueTogether(
            name="gameplayer",
            unique_together={("game", "user")},
        ),
        migrations.CreateModel(
            name="TournamentPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias_name",
                    models.CharField(
                        max_length=20, verbose_name="Tournament player's name"
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        default=0, verbose_name="Player' score in the tournament"
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        default=0, verbose_name="Player's rating in the tournament"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_players",
                        to="core.tournament",
                        verbose_name="Tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournaments_player",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "db_table": "tournament_player",
                "unique_together": {("tournament", "user")},
            },
        ),
        migrations.AddField(
            model_name="tournament",
            name="players",
            field=models.ManyToManyField(
                related_name="tournaments",
                through="core.TournamentPlayer",
                to="user.user",
                verbose_name="Tournament Players",
            ),
        ),
    ]
