# Generated by Django 5.0.3 on 2024-05-03 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tournament_number_of_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting all players confirmation'), (1, 'Scheduled'), (2, 'On going'), (3, 'Ended')], default=0, verbose_name='Tournament Status'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rules',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='tournament', to='core.gamerules', verbose_name='Tournament Rules'),
        ),
    ]
