# Generated by Django 5.0.3 on 2024-05-03 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tournament_status_alter_tournament_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='rules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tournament', to='core.gamerules', verbose_name='Tournament Rules'),
        ),
    ]
