# Generated by Django 5.0.3 on 2024-05-03 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_tournament_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='rules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.gamerules', verbose_name='Tournament Rules'),
        ),
    ]
