# Generated by Django 5.0.3 on 2024-05-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_tournament_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_datetime',
            field=models.DateTimeField(null=True, verbose_name='Game date'),
        ),
    ]
