# Generated by Django 5.0.3 on 2024-05-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_game_game_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.SmallIntegerField(choices=[(0, 'Challenge'), (1, 'Round-robin'), (2, 'Elimination')], default=0, verbose_name='Tournament Type'),
        ),
    ]
