# Generated by Django 5.0.3 on 2024-05-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_tournament_games_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaguePlayoff',
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-game_datetime'], 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending confirmation'), (1, 'Scheduled'), (2, 'Ongoing'), (3, 'Ended'), (4, 'Canceled')], default=1, verbose_name='Game status'),
        ),
    ]
