# Generated by Django 5.0.3 on 2024-05-06 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_leagueplayoff_alter_game_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 6, 21, 56, 49, 780894, tzinfo=datetime.timezone.utc), verbose_name='Tournament date'),
        ),
    ]
