# Generated by Django 5.0.3 on 2024-05-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tournament_tournament_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_date',
            field=models.DateField(verbose_name='Tournament date'),
        ),
    ]
