# Generated by Django 5.0.3 on 2024-05-26 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_tournament_tournament_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 26, 5, 5, 44, 25052, tzinfo=datetime.timezone.utc), verbose_name='Game date'),
        ),
    ]
