# Generated by Django 5.0.3 on 2024-05-26 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_game_duration_alter_game_game_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 26, 5, 10, 13, 778090, tzinfo=datetime.timezone.utc), verbose_name='Game date'),
        ),
        migrations.AlterField(
            model_name='gamerules',
            name='max_duration',
            field=models.DurationField(blank=True, default=None, null=True, verbose_name='Game maximum duration'),
        ),
    ]
