# Generated by Django 5.0.3 on 2024-06-09 17:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_game_game_datetime_and_more'),
        ('user', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 9, 17, 20, 58, 880340, tzinfo=datetime.timezone.utc), verbose_name='Game date'),
        ),
    ]
