# Generated by Django 5.0.3 on 2024-06-09 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_game_owner_tournament_owner_alter_game_game_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='players',
            new_name='_players',
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='position',
            field=models.IntegerField(choices=[(0, 'Left'), (1, 'Right')], default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 9, 17, 47, 42, 954700, tzinfo=datetime.timezone.utc), verbose_name='Game date'),
        ),
    ]
