# Generated by Django 5.0.3 on 2024-06-09 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_players_game__players_gameplayer_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 9, 18, 27, 38, 603231, tzinfo=datetime.timezone.utc), verbose_name='Game date'),
        ),
    ]
