# Generated by Django 5.0.3 on 2024-06-09 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_game_game_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Game date'),
        ),
    ]
