# Generated by Django 5.0.3 on 2024-06-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_game_game_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending confirmation'), (1, 'Scheduled'), (2, 'Ongoing'), (3, 'Paused'), (4, 'Ended'), (5, 'Canceled')], default=1, verbose_name='Game status'),
        ),
    ]
