# Generated by Django 5.0.3 on 2024-06-15 00:08

from django.db import migrations, models
from core.models import Tournament

def forwards(apps, schema_editor):
    TournamentsModel: models.Model = apps.get_model("core", "tournament")
    for t in TournamentsModel.objects.all():
        t: Tournament
        if t.name == "Tournament":
            t.name = t.__set_name()
            t.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_players_tournament__players'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='Tournament', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting all players confirmation'), (1, 'Scheduled'), (2, 'On going'), (3, 'Ended'), (4, 'Canceled')], default=0, verbose_name='Tournament Status'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.SmallIntegerField(choices=[(0, 'Challenge'), (1, 'Round-robin')], default=0, verbose_name='Tournament Type'),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
