# Generated by Django 5.0.3 on 2024-06-15 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_round_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='core.tournament'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='alias_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Alias name'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
    ]
