# Generated by Django 5.0.3 on 2024-06-15 19:12
from enum import IntEnum
from django.db import migrations, models
from core.models import Game


class GameStatus(IntEnum):
    ENDED = 4


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_round_tournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='_updated_players',
            field=models.BooleanField(default=False),
        ),
    ]
