# Generated by Django 5.0.3 on 2024-06-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_game__updated_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='_updated_players',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='_updated_players',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='ties',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='winnings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
