# Generated by Django 5.0.3 on 2024-06-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_tournament__updated_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='status',
            field=models.IntegerField(choices=[(0, "Didn't started"), (1, 'On going'), (2, 'Ended')], default=0, verbose_name='Tournament Status'),
        ),
    ]
