# Generated by Django 5.0.3 on 2024-06-16 16:16
from enum import IntEnum
from django.db import migrations, models


class TournamentStatus(IntEnum):
    ENDED = 3


class RoundStatus(IntEnum):
    ENDED = 2


def forwards(apps, schema_editor):
    TournamentModel: models.Model = apps.get_model("core", "tournament")
    RoundModel: models.Model = apps.get_model("core", "round")

    for t in TournamentModel.objects.filter(status=TournamentStatus.ENDED):
        for r in RoundModel.objects.filter(tournament__pk=t.pk):
            r.status = RoundStatus.ENDED
            r.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_tournament__updated_players_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Didn't started"), (1, "On going"), (2, "Ended")],
                default=0,
                verbose_name="Tournament Status",
            ),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
