# Generated by Django 5.0.3 on 2024-06-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_round_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
