# Generated by Django 5.0.3 on 2024-06-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending confirmation'), (1, 'Scheduled'), (2, 'Scheduled'), (3, 'Ongoing'), (4, 'Paused'), (5, 'Ended'), (6, 'Canceled')], default=2, verbose_name='Game status'),
        ),
    ]
