# Generated by Django 5.0.3 on 2024-06-26 23:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_tournament_tournament_date'),
        ('user', '0008_user_loaddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='_players',
            field=models.ManyToManyField(related_name='games', through='core.GamePlayer', to='user.user', verbose_name='Players'),
        ),
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='position',
            field=models.IntegerField(choices=[(0, 'Left'), (1, 'Right')], default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.IntegerField(choices=[(0, "Didn't started"), (1, 'On going'), (2, 'Ended')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='core.tournament', verbose_name='Tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='_players',
            field=models.ManyToManyField(related_name='tournaments', through='core.TournamentPlayer', to='user.user', verbose_name='Players'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='number_of_players',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Number of players'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='number_of_rounds',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Number of rounds'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.gamerules', verbose_name='Rules'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting all players confirmation'), (1, 'Scheduled'), (2, 'On going'), (3, 'Ended'), (4, 'Canceled')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.SmallIntegerField(choices=[(0, 'Challenge'), (1, 'Round-robin')], default=0, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='losses',
            field=models.PositiveIntegerField(default=0, verbose_name='Losses'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='ties',
            field=models.PositiveIntegerField(default=0, verbose_name='Ties'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_player', to='user.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='winnings',
            field=models.PositiveIntegerField(default=0, verbose_name='Winnings'),
        ),
    ]
