version: '3.8'

services:
  game-db:
    container_name: game-db
    image: postgres
    volumes:
      - game-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${GAME_DB_USER}
      - POSTGRES_PASSWORD=${GAME_DB_PASSWORD}
      - POSTGRES_DB=${GAME_DB}
    restart: unless-stopped
    ports:
      - "5434:5432"

  game-api:
    container_name: game-api
    build: ./
    volumes:
      - ./:/api
    ports:
      - "8003:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${GAME_DB_USER}
      - POSTGRES_PASSWORD=${GAME_DB_PASSWORD}
      - POSTGRES_DB=${GAME_DB}
      - POSTGRES_HOST=game-db
      # - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - game-db

volumes:
  game-db-data:
