# Generated by Django 5.0.3 on 2024-04-21 02:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_ref', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
