# Generated by Django 5.0.3 on 2024-06-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='/media/avatars/default_avatar.jpeg', max_length=255),
        ),
    ]
