# Generated by Django 5.0.3 on 2024-05-07 02:46
from django.db import migrations, models


users = [
    {
        "pk": "355aaf65-0300-47b6-8748-c8d0c1aed702",
        "fields": {
            "username": "brunobonaldi",
            "avatar": "/media/avatars/default_avatar.jpeg",
            "score": 350,
            "rating": 50,
            "winnings": 17,
            "losses": 24,
            "ties": 2,
        },
    },
    {
        "pk": "38b8cb4d-34d8-4530-80f3-b4f10cf87b51",
        "fields": {
            "username": "shelson",
            "avatar": "/media/avatars/default_avatar.jpeg",
            "score": 319,
            "rating": 48,
            "winnings": 16,
            "losses": 20,
            "ties": 4,
        },
    },
    {
        "pk": "9a72c344-62c3-49c3-9bca-188f6f7b3cbe",
        "fields": {
            "username": "sheela",
            "avatar": "/media/avatars/default_avatar.jpeg",
            "score": 383,
            "rating": 64,
            "winnings": 22,
            "losses": 15,
            "ties": 2,
        },
    },
    {
        "pk": "9c001ba9-14d5-45ff-a4a4-4f43234dcdd7",
        "fields": {
            "username": "eliaris",
            "avatar": "/media/avatars/default_avatar.jpeg",
            "score": 458,
            "rating": 55,
            "winnings": 19,
            "losses": 19,
            "ties": 3,
        },
    },
    {
        "pk": "e054f322-7733-48be-b1b1-7a66357efecd",
        "fields": {
            "username": "humberto",
            "avatar": "/media/avatars/default_avatar.jpeg",
            "score": 392,
            "rating": 57,
            "winnings": 20,
            "losses": 16,
            "ties": 1,
        },
    },
]


def forwards(apps, schema_editor):
    UserModel: models.Model = apps.get_model("user", "User")

    for u in users:
        user = UserModel.objects.filter(id=u["pk"], username=u["fields"]["username"])
        if not user.exists():
            user = UserModel.objects.create(id=u["pk"], **u["fields"])


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_user_losses_user_rating_user_score_user_ties_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
