# Generated by Django 3.2.25 on 2024-05-02 16:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_api', '0002_auto_20240429_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chosen_language',
            field=models.CharField(default='en', max_length=255),
        ),
    ]
