# Generated by Django 3.2.25 on 2024-05-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_api', '0003_auto_20240502_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
