# Generated by Django 3.2.25 on 2024-05-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_api', '0004_alter_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='user_uuid',
        ),
    ]
