# Generated by Django 3.2.25 on 2024-05-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_api', '0006_user_avatar_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_name',
        ),
        migrations.AddField(
            model_name='friendshiprequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.jpeg', null=True, upload_to='avatars/'),
        ),
    ]
