# Generated by Django 3.2.25 on 2024-05-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_api', '0009_auto_20240518_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
