# Generated by Django 3.2.25 on 2024-06-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_api', '0011_auto_20240617_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeduser',
            name='blocked_user_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='user_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='friendship',
            name='friend_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='friendship',
            name='user_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
