# Generated by Django 3.2.25 on 2024-06-19 01:26

from django.db import migrations, models
import uuid
from django.contrib.auth.hashers import make_password

def create_initial_data(apps, schema_editor):
    User = apps.get_model('user_management_api', 'User')
    Friendship = apps.get_model('user_management_api', 'Friendship')
    FriendshipRequest = apps.get_model('user_management_api', 'FriendshipRequest')

    users = [
        {
            "id": uuid.UUID("9a72c344-62c3-49c3-9bca-188f6f7b3cbe"),
            "email": "sheela.khusal.08@gmail.com",
            "nickname": "sheela",
            "status": "active",
            "user_uuid": "9a72c344-62c3-49c3-9bca-188f6f7b3cbe",
            "name": "Sheela",
            "avatar": "avatars/default_avatar.jpeg"
        },
        {
            "id": uuid.UUID("355aaf65-0300-47b6-8748-c8d0c1aed702"),
            "email": "brunobonaldi1994@gmail.com",
            "nickname": "brunobonaldi",
            "status": "active",
            "user_uuid": "355aaf65-0300-47b6-8748-c8d0c1aed702",
            "name": "Bruno",
            "avatar": "avatars/default_avatar.jpeg"
        },
        {
            "id": uuid.UUID("38b8cb4d-34d8-4530-80f3-b4f10cf87b51"),
            "email": "shelsonx@gmail.com",
            "nickname": "shelson",
            "status": "active",
            "user_uuid": "38b8cb4d-34d8-4530-80f3-b4f10cf87b51",
            "name": "Shelson",
            "avatar": "avatars/default_avatar.jpeg"
        },
        {
            "id": uuid.UUID("9c001ba9-14d5-45ff-a4a4-4f43234dcdd7"),
            "email": "eliarisalvares@gmail.com",
            "nickname": "eliaris",
            "status": "active",
            "user_uuid": "9c001ba9-14d5-45ff-a4a4-4f43234dcdd7",
            "name": "Eliaris",
            "avatar": "avatars/default_avatar.jpeg"
        },
        {
            "id": uuid.UUID("e054f322-7733-48be-b1b1-7a66357efecd"),
            "email": "humberto.arndt@gmail.com",
            "nickname": "humberto",
            "avatar": "avatars/default_avatar.jpeg",
            "status": "active",
            "user_uuid": "e054f322-7733-48be-b1b1-7a66357efecd",
            "name": "Humberto",
            "avatar": "avatars/default_avatar.jpeg"
        },
    ]

    user_instances = [User(**user_data) for user_data in users]
    User.objects.bulk_create(user_instances)

    # Create some friendships
    friendships = [
        {
            "user_id": uuid.UUID("9a72c344-62c3-49c3-9bca-188f6f7b3cbe"),
            "friend_id": uuid.UUID("355aaf65-0300-47b6-8748-c8d0c1aed702"),
        },
        {
            "user_id": uuid.UUID("38b8cb4d-34d8-4530-80f3-b4f10cf87b51"),
            "friend_id": uuid.UUID("9c001ba9-14d5-45ff-a4a4-4f43234dcdd7"),
        },
        {
            "user_id": uuid.UUID("e054f322-7733-48be-b1b1-7a66357efecd"),
            "friend_id": uuid.UUID("9a72c344-62c3-49c3-9bca-188f6f7b3cbe"),
        }
    ]

    friendship_instances = [Friendship(**friendship_data) for friendship_data in friendships]
    Friendship.objects.bulk_create(friendship_instances)

    # Create some friendship requests
    friendship_requests = [
        {
            "sender_id": uuid.UUID("9c001ba9-14d5-45ff-a4a4-4f43234dcdd7"),
            "receiver_id": uuid.UUID("38b8cb4d-34d8-4530-80f3-b4f10cf87b51"),
        },
        {
            "sender_id": uuid.UUID("355aaf65-0300-47b6-8748-c8d0c1aed702"),
            "receiver_id": uuid.UUID("9a72c344-62c3-49c3-9bca-188f6f7b3cbe"),
        }
    ]

    friendship_request_instances = [FriendshipRequest(**friendship_request_data) for friendship_request_data in friendship_requests]
    FriendshipRequest.objects.bulk_create(friendship_request_instances)

class Migration(migrations.Migration):

    dependencies = [
        ('user_management_api', '0012_auto_20240617_1907'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]


