# Generated by Django 3.2.25 on 2024-06-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_api', '0014_user_avatar_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blockeduser',
            unique_together={('user', 'blocked_user')},
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('user', 'friend')},
        ),
        migrations.AlterUniqueTogether(
            name='friendshiprequest',
            unique_together={('sender', 'receiver')},
        ),
    ]
