version: '3.8'

services:

  #change the database name
  auth-db:
    image: postgres
    volumes:
      #change the volume name
      - auth-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # add in the .env the name of the db
      - POSTGRES_DB=${POSTGRES_AUTH_DB}
    ports:
      - "5433:5432"

  auth-api:
    build: ./services/auth
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./services/auth:/code
    ports:
      - "8002:80"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # add in the .env the name of the db
      - POSTGRES_NAME=${POSTGRES_AUTH_DB}
      # this must be the name of the db service
      - POSTGRES_HOST=auth-db
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - auth-db

volumes:
  #change the volume name
  auth-db-data: