# Generated by Django 5.0.1 on 2024-02-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="enable_2fa",
            field=models.BooleanField(default=False),
        ),
    ]
