# Generated by Django 5.0.1 on 2024-02-24 23:08

from django.db import migrations
from ..constants.login_type_constants import LoginTypeConstants

def create_login_type(apps, schema_editor):
    LoginType = apps.get_model('app', 'LoginType')
    LoginType.objects.create(name=LoginTypeConstants.AUTH_EMAIL)
    LoginType.objects.create(name=LoginTypeConstants.AUTH_42)

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_login_type)
    ]
