# Generated by Django 5.0.1 on 2024-03-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_basesignupdto_signindto_signinupoauth42dto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
