# Generated by Django 5.0.1 on 2024-05-01 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_twofactor_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactor',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 21, 49, 13, 993254, tzinfo=datetime.timezone.utc)),
        ),
    ]
