# Generated by Django 5.0.1 on 2024-05-04 18:20

import app.models.two_factor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_twofactor_expiration_alter_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactor',
            name='expiration',
            field=models.DateTimeField(default=app.models.two_factor.default_expiration),
        ),
    ]
