# Generated by Django 5.0.1 on 2024-05-01 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_twofactor_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactor',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 21, 51, 56, 944451, tzinfo=datetime.timezone.utc)),
        ),
    ]
