# Generated by Django 5.0.1 on 2024-06-12 01:40

import app.models.two_factor_game
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_user_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration', models.DateTimeField(default=app.models.two_factor_game.default_expiration)),
                ('game_type', models.CharField(choices=[('INDIVIDUAL_GAME', 'Individual Game'), ('TOURNAMENT', 'Tournament')], default='INDIVIDUAL_GAME', max_length=50)),
                ('game_id', models.BigIntegerField()),
                ('user_receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_games', to='app.user')),
                ('user_requester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_games', to='app.user')),
            ],
        ),
    ]
