# Generated by Django 5.0.1 on 2024-06-15 17:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_twofactorgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendGame2FactorCodeDto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_receiver_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('user_requester_id', models.UUIDField()),
                ('game_type', models.CharField(choices=[('INDIVIDUAL_GAME', 'Individual Game'), ('TOURNAMENT', 'Tournament')], default='INDIVIDUAL_GAME', max_length=50)),
                ('game_id', models.BigIntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ValidateGame2FactorCodeDto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_requester_id', models.UUIDField()),
                ('code_user_receiver_id', models.JSONField(blank=True, null=True)),
                ('game_id', models.BigIntegerField()),
                ('game_type', models.CharField(choices=[('INDIVIDUAL_GAME', 'Individual Game'), ('TOURNAMENT', 'Tournament')], default='INDIVIDUAL_GAME', max_length=50)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
